# This playbook creates AWS instances of type micro

#- name: AWS spawn instances
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ec2_access_key: ""
    ec2_secret_key: ""

  tasks:
    - name: create a set of instances
      ec2:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        key_name: sydney
        #group: VirginiaSecurity
        #group_id: sg-3ddf4f4c
        instance_type: t2.micro
        image: ami-10918173
        wait: true
        exact_count: 1
        region: ap-southeast-2
        count_tag:
          Name: demo
        instance_tags:
          Name: demo
      register: ec2
# - hosts: localhost
#   connection: local
#   tasks:
#     - name: terminate instances
#       ec2:
#         region: us-east-1
#         state: absent
#         instance_ids: "{{ec2.instance_ids}}"
