- name: Playbook to add ssh key for authorized access
  hosts: hostvirtual
  become: true
  vars:
   - filepath: '{{ file }}'
  tasks:
   - name: Set authorized key took from file
     authorized_key:
       user: root 
       state: present
       key: "{{ lookup('file', '{{ filepath }}') }}"
